-- SQLBook: Code
USE ParkingLot;

ALTER TABLE Customers
MODIFY FirstName VARCHAR(50) NOT NULL,
MODIFY LastName VARCHAR(50) NOT NULL,
MODIFY PhoneNumber VARCHAR(20) NOT NULL,
ADD CONSTRAINT Unique_PhoneNumber UNIQUE (PhoneNumber);

ALTER TABLE Vehicles
MODIFY Type VARCHAR(50) NOT NULL,
MODIFY Brand VARCHAR(50) NOT NULL,
MODIFY Color VARCHAR(20) NOT NULL;

ALTER TABLE Services
MODIFY ServiceName VARCHAR(100) NOT NULL,
MODIFY ServicePrice DECIMAL(10, 2) NOT NULL,
ADD CONSTRAINT Check_ServicePrice CHECK (ServicePrice > 0),
MODIFY VehicleType VARCHAR(50) NOT NULL;

ALTER TABLE ServiceRegistration
MODIFY ServiceID INT NOT NULL,
MODIFY LicensePlate VARCHAR(15) NOT NULL,
MODIFY StartTime DATETIME NOT NULL;

ALTER TABLE ParkingLot
MODIFY ParkName VARCHAR(50) NOT NULL,
MODIFY Capacity INT NOT NULL,
ADD CONSTRAINT Check_Capacity CHECK (Capacity > 0);


ALTER TABLE Tickets
MODIFY LicensePlate VARCHAR(15) NOT NULL,
MODIFY IssuedTime DATETIME NOT NULL,
MODIFY ServiceID INT NOT NULL,
ADD CONSTRAINT Unique_LicensePlate UNIQUE (LicensePlate);

ALTER TABLE Employees
MODIFY FirstName VARCHAR(50) NOT NULL,
MODIFY LastName VARCHAR(50) NOT NULL,
MODIFY PhoneNumber VARCHAR(20) NOT NULL,
ADD CONSTRAINT Unique_PhoneNumber UNIQUE (PhoneNumber);

ALTER TABLE Shifts
MODIFY StartTime TIME NOT NULL,
MODIFY EndTime TIME NOT NULL;

ALTER TABLE ShiftsDetails
MODIFY EmployeeID INT NOT NULL,
MODIFY ShiftID INT NOT NULL,
MODIFY ParkID INT NOT NULL;
